name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
        # os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: sudo apt-get install -y build-essential

    - name: Make (Ubuntu)
      if: runner.os == 'Linux'
      run: make

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install make mingw -y
        choco install tdmgcc -y

    - name: Make (Windows)
      if: runner.os == 'Windows'
      run: mingw32-make.exe CC="gcc" release 

    - name: Determine binary extension
      id: artifact_ext
      run: echo "::set-output name=ext::$(if [[ "${{ runner.os }}" == "Windows" ]]; then echo '.exe'; else echo ''; fi)"

    - name: Create build directory and copy binary
      run: |
        mkdir build
        cp ./rayforce${{ steps.artifact_ext.outputs.ext }} ./build/  
        cd build
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          7z a ../rayforce.zip .
        else
          zip -r ../rayforce.zip .
        fi

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }} 
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./rayforce.zip
        asset_name: ${{ matrix.os }}.zip
        asset_content_type: application/zip
